export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'ex-bg': 'var(--ex-bg)',
        'ex-bg-alt': 'var(--ex-bg-alt)',
        'ex-surface': 'var(--ex-surface)',
        'ex-surface-muted': 'var(--ex-surface-muted)',
        'ex-surface-hover': 'var(--ex-surface-hover)',
        'ex-border': 'var(--ex-border)',
        'ex-border-strong': 'var(--ex-border-strong)',
        'ex-divider': 'var(--ex-divider)',
        'ex-text': 'var(--ex-text)',
        'ex-text-muted': 'var(--ex-text-muted)',
        'ex-text-subtle': 'var(--ex-text-subtle)',
        'ex-primary': 'var(--ex-primary)',
        'ex-primary-hover': 'var(--ex-primary-hover)',
        'ex-primary-active': 'var(--ex-primary-active)',
        'ex-primary-soft': 'var(--ex-primary-soft)',
        'ex-primary-soft-hover': 'var(--ex-primary-soft-hover)',
        'ex-danger': 'var(--ex-danger)',
        'ex-danger-hover': 'var(--ex-danger-hover)',
        'ex-danger-soft': 'var(--ex-danger-soft)',
        'ex-success': 'var(--ex-success)',
        'ex-success-soft': 'var(--ex-success-soft)',
        'ex-warning': 'var(--ex-warning)',
        'ex-warning-soft': 'var(--ex-warning-soft)',
      },
      borderRadius: {
        'ex-sm': 'var(--ex-radius-sm)',
        'ex': 'var(--ex-radius)',
        'ex-lg': 'var(--ex-radius-lg)',
        'ex-xl': 'var(--ex-radius-xl)',
      },
      boxShadow: {
        'ex-island': 'var(--ex-shadow-island)',
        'ex-raised': 'var(--ex-shadow-raised)',
        'ex-soft': 'var(--ex-shadow-soft)',
      },
      fontFamily: {
        excali: ['Excalifont', 'Assistant', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
